import { Link } from "wouter";
import { ArrowRight, Check, ChevronDown } from "lucide-react";
import { PublicFooter, PublicHeader } from "./About";

const pages: Record<string, { kicker: string; title: string; intro: string; sections: { title: string; text: string }[] }> = {
  features: { kicker: "Produkt", title: "Alles, was Zusammenarbeit leichter macht.", intro: "Ein gemeinsamer Ort für Bestellungen, Lieferanten, Dokumente und Gespräche — klar strukturiert für den Alltag.", sections: [["Katalog & Preisvergleich", "Produkte entdecken, Anbieter vergleichen und Entscheidungen mit aktuellen Informationen treffen."], ["Bestellungen & Kommunikation", "Jeder Vorgang bleibt nachvollziehbar. Fragen, Änderungen und Reklamationen sind direkt am richtigen Kontext."], ["Dokumente & Kennzahlen", "Lieferscheine, Rechnungen und Auswertungen stehen dort bereit, wo sie gebraucht werden."]] .map(([title, text]) => ({ title, text })) },
  "how-it-works": { kicker: "Ablauf", title: "Von der Anfrage bis zur Lieferung.", intro: "GastroConnect verbindet die Schritte, die heute oft über mehrere Kanäle verteilt sind.", sections: [["01 — Zugang", "Starten Sie als Betrieb oder Händler und richten Sie Ihren Unternehmensbereich ein."], ["02 — Partner", "Finden Sie passende Partner, teilen Sie Informationen und bauen Sie verlässliche Beziehungen auf."], ["03 — Alltag", "Bestellen, bestätigen, liefern und auswerten — mit einem klaren Status für alle Beteiligten."]] .map(([title, text]) => ({ title, text })) },
  contact: { kicker: "Kontakt", title: "Sprechen wir über Ihren Alltag.", intro: "Sie möchten GastroConnect kennenlernen oder mit Ihrem Unternehmen starten? Schreiben Sie uns.", sections: [["E-Mail", "hello@gastroconnect.app"], ["Für Betriebe", "Erzählen Sie uns, welche Abläufe Sie vereinfachen möchten."], ["Für Händler", "Zeigen Sie Ihren Kunden Ihr Sortiment an einem zentralen Ort."]] .map(([title, text]) => ({ title, text })) },
  impressum: { kicker: "Rechtliches", title: "Impressum", intro: "Angaben gemäß den gesetzlichen Bestimmungen.", sections: [{ title: "GastroConnect", text: "Digitale Plattform für die Lebensmittelversorgung und Gastronomie. Für geschäftliche Anfragen erreichen Sie uns unter hello@gastroconnect.app." }] },
  datenschutz: { kicker: "Rechtliches", title: "Datenschutz", intro: "Transparenz und ein verantwortungsvoller Umgang mit Daten gehören zu unserem Fundament.", sections: [{ title: "Grundsatz", text: "Wir verarbeiten personenbezogene Daten nur, wenn dies für den Betrieb, die Sicherheit oder die Kommunikation der Plattform erforderlich ist. Details zu Ihren Rechten und Speicherdauern erhalten Sie auf Anfrage." }] },
  agb: { kicker: "Rechtliches", title: "Allgemeine Geschäftsbedingungen", intro: "Die Regeln für eine verlässliche Nutzung von GastroConnect.", sections: [{ title: "Geltungsbereich", text: "Diese Seite informiert über die Grundlage der Nutzung von GastroConnect durch Unternehmen und ihre eingeladenen Mitarbeitenden. Die vollständigen Bedingungen werden vor dem Vertragsabschluss bereitgestellt." }] },
};

export default function PublicInfo({ type }: { type: string }) {
  const page = pages[type] ?? pages.features;
  const isFaq = type === "faq";
  return <div className="gc-public min-h-screen bg-white text-[#171918]"><PublicHeader /><main className="mx-auto max-w-7xl px-5 pb-24 pt-20 md:px-10 md:pb-36 md:pt-32"><p className="gc-kicker">{isFaq ? "Fragen & Antworten" : page.kicker}</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-8xl">{isFaq ? <>Gut zu wissen. <span className="gc-accent">Kurz erklärt.</span></> : page.title}</h1><p className="gc-long mt-10 max-w-2xl text-2xl leading-tight text-black/60 md:text-4xl">{isFaq ? "Die wichtigsten Antworten rund um GastroConnect, Zugang und Zusammenarbeit." : page.intro}</p><div className="mt-20 grid max-w-4xl border-t border-black/15">{(isFaq ? [["Wer kann GastroConnect nutzen?", "Betriebe und Händler aus der Gastronomie arbeiten auf GastroConnect in getrennten, passenden Bereichen zusammen."], ["Wie starte ich?", "Wählen Sie Ihre Rolle und registrieren Sie Ihr Unternehmen. Nach der Prüfung erhalten Sie Zugang."], ["Ist die Plattform kostenlos?", "Kontaktieren Sie uns für die passende Lösung für Ihr Unternehmen."]] : page.sections.map(s => [s.title, s.text])).map(([title, text]) => <article key={title} className="grid gap-4 border-b border-black/15 py-8 md:grid-cols-[.7fr_1.3fr]"><h2 className="text-xl font-semibold">{title}</h2><p className="gc-long text-lg leading-relaxed text-black/60">{text}</p>{isFaq && <ChevronDown className="hidden md:block" />}</article>)}</div><Link href="/register" className="mt-12 inline-flex items-center gap-2 rounded-full bg-[#171918] px-6 py-3 text-sm text-white">GastroConnect entdecken <ArrowRight className="h-4 w-4" /></Link></main><PublicFooter /></div>;
}